import {StyleSheet} from 'react-native'
import { palette } from '../../theme'
export default StyleSheet.create({
    containTheme:{
        marginVertical:16,
        marginHorizontal:16
    },
    theme:{
        fontSize:25,
        fontWeight:'bold'
    },
    questionPermanent:{
        fontSize:17,
        color:'#5C5B5B',
        marginTop:8
    },
    questionContain:{
        marginHorizontal:16,
    },
    lessonTheme:{
        fontSize:24,
        fontWeight:'bold'
    },
    list:{
        fontSize:17,
        color:'#868686',
        marginTop:8
    },
    containLessonTheme:{
        marginHorizontal:16,
        marginTop:16
    },
    imageIcon:{
        flex:1,
        resizeMode:"contain",
        width:undefined,
        height:25
    },
    containScore:{
        flexDirection:'row',
        marginTop:8
    },
    score:{
        fontSize:15,
        padding:4,
        fontWeight:'bold',
        color:'#F49608'
    },
    title:{
        fontSize:17,
        fontWeight:'bold',
    },
    contain:{
        backgroundColor:'#E5E5E5',
        borderRadius:20
    },
    iconPlay:{
        justifyContent:'center',
        flex:1
    },
    containAllTitle:{
        flexDirection:'row',
        marginHorizontal:32,
        marginVertical:8
    },
    line:{
        borderLeftWidth:1,
        height:50,
        marginLeft:16,
        borderLeftColor:palette.textInputBorderBottom
    },
    answerQuestion:{
        alignSelf:'center',
        fontSize:17,
        fontWeight:'bold'
    },
    ButtonForm:{
        marginHorizontal:64,
        marginTop:64,
        marginBottom:64,
      
    }
})