import {StyleSheet} from 'react-native'
import { fontSize, palette } from '../../theme'
export default StyleSheet.create({
    containHead:{
        backgroundColor:palette.white,
        flex:1,
        marginTop:8,
        flexDirection:'row',
        marginBottom:16,
        borderBottomWidth:0.5
    },
    containTextView:{
        flex:1,
        alignItems:'center',
        marginTop:8,
        fontSize:fontSize[4],
        fontWeight:'bold',
        textAlign:'center',
        paddingBottom:16
    },
    img:{
        height:850,
        borderRadius:20,
        width:'100%',
        flex:1
    },
    containImg:{
        marginHorizontal:16,
        elevation:9,
        marginBottom:16,
        flex:1
    },
    detailCoupon:{
        position:'absolute',
        flex:1,
        backgroundColor:palette.white,
        width:'90%',
        marginTop:16,
        alignSelf:'center',
        height:200,
        borderRadius:10,
        elevation:10
    },
    contaiNameStore:{
        marginTop:16
    },
    name:{
       paddingHorizontal:16,
       fontWeight:'bold',
       fontSize:fontSize[4]
    },
    detail:{
        paddingHorizontal:16,
        marginTop:4,
        fontSize:fontSize[3],
        color:palette.grey
    },
    containHansd:{
        flex:1,
        justifyContent:'flex-end',
        marginBottom:8,
        marginLeft:16
    },
    hansd:{
        fontSize:fontSize[3],
        color:palette.grey
    },
    time:{
        fontSize:fontSize[4],
        fontWeight:'bold',
        color:'#008ae6'
    },
    containButton:{
        marginBottom:16,
        marginLeft:16,
        backgroundColor:'tomato',
        borderRadius:5,
        alignItems:'center',
        width:80
    },
    textreceive:{
        paddingVertical:8,
        fontWeight:'bold',
        color:palette.white,
        fontSize:fontSize[3]
    }
})