import {StyleSheet} from 'react-native'
import { palette } from '../../theme'
export default StyleSheet.create({
    lessonTheme:{
        fontSize:24,
        fontWeight:'bold'
    },
    list:{
        fontSize:17,
        color:'#868686',
        marginTop:8
    },
    containLessonTheme:{
        marginHorizontal:16,
        marginTop:16
    },
    imageIcon:{
        flex:1,
        resizeMode:"contain",
        width:undefined,
        height:25
    },
    containScore:{
        flexDirection:'row',
        marginTop:8
    },
    score:{
        fontSize:15,
        padding:4,
        fontWeight:'bold',
        color:'#F49608'
    },
    title:{
        fontSize:17,
        fontWeight:'bold',
    },
    contain:{
        backgroundColor:'#E5E5E5',
        borderRadius:20,
        flexDirection:'row',
        flex:1,
        marginBottom:16
    },
    iconPlay:{
       justifyContent:'center',
       marginRight:8
    },
    containAllTitle:{
        flex:1,
        marginLeft:32,
        marginVertical:8
    },
    line:{
        borderLeftWidth:1,
        height:50,
        marginLeft:16,
        borderLeftColor:palette.textInputBorderBottom,
    },
    iconLock:{
 
        flexDirection:"row"
    }
})