import {StyleSheet} from 'react-native'
import { fontSize, palette } from '../../theme'
export default StyleSheet.create({
    header:{
        flexDirection:'row',
        paddingVertical:8,
        paddingHorizontal:16,
        borderBottomWidth:0.4
    },
    imgava:{
        resizeMode:'contain',
        width:undefined,
        height:120,
        borderRadius:200,
    },
    containava:{
        paddingTop:32,
        backgroundColor:palette.backgroundlightGreen
    },
    titleName:{
        alignSelf:'center',
        fontSize:fontSize[6],
        marginTop:16,
        marginBottom:32,
        fontWeight:'bold'
    },
    imgcoin:{
        width:30,
        height:30,
        marginRight:8,
        marginVertical:4
    },
    containTS:{
        flexDirection:'row',
        backgroundColor:'tomato',  
        flex:1,
        alignSelf:'flex-end',
        marginRight:16,
        borderRadius:5,
        marginTop:16
    },
    titleTS:{
        paddingHorizontal:8,
        alignSelf:'center',
        fontSize:fontSize[3],
        fontWeight:'bold'
    },
    titleTK:{
        fontSize:fontSize[4]
    },
    containTK:{
        flexDirection:'row',
        marginTop:16
    },
    descrip:{
        fontSize:fontSize[4],
        color:palette.grey
    },
    line:{
        borderWidth:0.4,
        borderColor:palette.grey,
        marginTop:16,
    }
})