import {StyleSheet} from 'react-native'
import { fontSize, palette } from '../../theme'
export default StyleSheet.create({
    ImageLogo:{
        resizeMode:"contain",
        width:undefined,
        height:25,
        marginTop:12,
        flex:1
    },
    header:{
        flexDirection:'row',
        borderBottomWidth:0.4,
    },
    imageHeader:{
        resizeMode:'contain',
        width:undefined,
        height:85,
        marginTop:32
    },
    imgava:{
        width:95,
        height:95,
        borderRadius:200,
        alignSelf:'center'
    },
    containava:{
        paddingTop:16,
   
    },
    titleName:{
        alignSelf:'center',
        fontSize:fontSize[0],
        marginTop:16,
        marginBottom:16,
        fontWeight:'bold'
    },
    imgcoin:{
        width:30,
        height:30,
        marginRight:8,
        marginVertical:4
    },
    containTS:{
        flexDirection:'row',
        backgroundColor:'tomato',
        alignSelf:'flex-end',
        marginRight:32,
        borderRadius:5,
        marginTop:16
    },
    titleTS:{
        paddingHorizontal:8,
        alignSelf:'center',
        fontSize:fontSize[3],
        fontWeight:'bold',
        color:'white'
    },
    contain:{
        marginHorizontal:32,
        elevation:2,
        borderRadius:10,
        paddingBottom:20
    },
    icon:{
        height:30,
        width:35,
        
    },
    containInfo:{
        flexDirection:'row',
        marginTop:20,
        marginHorizontal:24
    },
    info:{
        color:palette.grey,
        fontWeight:'bold',
        marginVertical:16,
        marginLeft:32
    },
    infotext:{
        color:palette.grey,
        alignSelf:'center',
        marginLeft:20,
        flex:1
    },
    containerSwitch:{
        flexDirection:'row',
        marginHorizontal:32,
        
    },
    buttonSwitch:{
        flex:1
    },
    titleSwitch:{
        fontWeight:'bold',
        fontSize:fontSize[4],
        color:palette.grey
    }
})