import {StyleSheet} from 'react-native'
import { fontSize, palette } from '../../theme'
export default StyleSheet.create({
    headContain:{
        flexDirection:'row',
        marginTop:16,
        borderBottomWidth:0.7,
        borderBottomColor:palette.colorgray
    },
    imgLogo:{
        resizeMode:'contain',
        width:undefined,
        height:25,
        marginBottom:16
    },
    textCancel:{
        fontSize:fontSize[4],
        color:palette.grey
    },
    textPost:{
        fontSize:fontSize[4],
        fontWeight:'bold',
        color:palette.buttonColor
    },
    containTextCancel:{
        marginLeft:16
    },
    containTextPost:{
        marginRight:16
    },
    containTextInput:{
        flex:1
    },
    TextInput:{
        fontSize:fontSize[4],
        paddingHorizontal:16
    },
    containAddImage:{
        flexDirection:'row',
        marginLeft:16
    },
    textAddImage:{
        alignSelf:'center',
        marginLeft:4,
        fontSize:fontSize[3],
        color:"#595959",
        fontWeight:'bold'
    },
    containAddLink:{
        flexDirection:'row',
        marginLeft:16
    },
    textAddLink:{
        fontWeight:'bold',
        alignSelf:'center',
        alignSelf:'center',
        marginLeft:4,
        fontSize:fontSize[3],
        color:"#595959",
        fontWeight:'bold'
    },
    containAdd:{
        flexDirection:'row'
    },
    themeContain:{
        backgroundColor:"#C4C4C4",
        marginLeft:16,
        borderRadius:20
    },
    textTheme:{
        paddingVertical:4,
        paddingHorizontal:12,
        color:'#595959',
        fontWeight:'bold'
    },
    containTouchTheme:{
        flexDirection:'row',
        marginLeft:16,
        marginTop:16
    },
    theme:{
        color:'#595959',
        alignSelf:'center',
        fontSize:fontSize[4]
    },
    containFooter:{
        alignSelf: 'flex-end',
        position: 'absolute',
        left: 0,
        bottom:0,
        flex:1,
        width:'100%',
        paddingVertical:16,
        backgroundColor:'white',
        borderTopWidth:0.4
    },
    imgUpload:{
        height:80,
        width:80,
        borderRadius:10
    },
    iconClose:{
        position:'absolute',
        marginLeft:70,
        backgroundColor:'tomato',
        borderRadius:30, 
        paddingHorizontal:2,
        paddingVertical:2
    }
})