import {StyleSheet} from 'react-native'
export default StyleSheet.create({
    ImageLogo:{
        resizeMode:"contain",
        width:undefined,
        height:25,
        flex:1,
        marginTop:12,
        marginBottom:16
    },
    header:{
        flexDirection:'row',
        borderBottomWidth:0.4,
        flex:1
    },
    imageCover:{
        flex:1,
        resizeMode:'cover',
        width:undefined,
        height:236
    },
    imageLogo2:{
        width:120,
        height:40,
    },
    calendar:{
        flex:1,flexDirection:'row',justifyContent:'flex-end'
    },
    datetime:{
        marginLeft:4,
        alignItems:'center',
        fontSize:15,
        color:'#5C5B5B'
    },
    headNews:{
        flexDirection:'row',marginHorizontal:16,
        marginTop:16
    },
    containtitleNews:{
        flex:1,
        marginHorizontal:16
    },
    titleNews:{
        fontSize:30,
        fontWeight:'bold'
    },
    buttonLikeAndDis:{
        flex:1,
        borderTopWidth:0.4,
        borderBottomWidth:0.4,
        height:50,
        marginTop:16,
        flexDirection:'row'
    },
    buttonLike:{
        flexDirection:'row',
        alignItems:'center',
        marginLeft:64
    },
    countLike:{
        fontSize:17,
        color:"#5C5B5B",
        marginLeft:4
    },
    ButtonDislike:{
        flex:1,
        flexDirection:'row',
        justifyContent:'flex-end',
        alignItems:'center',
        marginRight:64
    },
    WriteNews:{
        marginHorizontal:16,
        flex:1,
        marginVertical:16
    },
    WriteNewsTitle:{
        fontSize:17,
        color:'#524747'
    }
})